---
- name: Pull and Run docker image of mini project
  hosts: all
  tasks:
    - name: Pull khushboo85/mini
      docker_image:
        name: khushalways/pet-portal-dockerimage
        source: pull
      
    - name: spin up application using docker-compose 
      shell:
              cmd: docker run -d -it  -p 80:80/tcp khushalways/pet-portal-dockerimage